name: aqyl_school
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'


dependencies:
  auto_route: ^6.3.0
  auto_route_generator: ^6.2.0
  bloc: ^8.1.1
  connectivity_plus: ^3.0.4
  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  dartz: ^0.10.1
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  equatable: ^2.0.3
  google_sign_in: ^5.2.1
  email_validator: ^2.0.1


  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  injectable: ^2.1.1
  intl: ^0.18.1
  json_annotation: ^4.8.0
  keyboard_actions: ^4.2.0
  responsive_sizer: ^3.1.1
  shared_preferences: ^2.1.0


dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
